server:
  port: 8084
  servlet:
    application-display-name: option

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/opt?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    # class-name=org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format-sql: true
      hibernate.show-sql: true

jwt:
  secret:
    salt: ty
    expire-day: 1d
    header-auth: token
